-- 1. CREATE THE TABLE
CREATE TABLE IF NOT EXISTS enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  type TEXT NOT NULL,
  name TEXT,
  email TEXT,
  phone_number TEXT,
  message TEXT,
  plan_days INTEGER,
  amount NUMERIC,
  status TEXT DEFAULT 'new'
);

-- 2. ENABLE REAL-TIME
-- Note: Check if publication exists or handle error
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
  ALTER PUBLICATION supabase_realtime ADD TABLE enquiries;
EXCEPTION
  WHEN OTHERS THEN
    -- Ignore error if table is already in project publication
    NULL;
END $$;

-- 3. ENABLE SECURITY (RLS)
ALTER TABLE enquiries ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid duplicates
DROP POLICY IF EXISTS "Allow anon inserts" ON enquiries;
DROP POLICY IF EXISTS "Allow admin select" ON enquiries;
DROP POLICY IF EXISTS "Allow admin update" ON enquiries;
DROP POLICY IF EXISTS "Allow admin delete" ON enquiries;

CREATE POLICY "Allow anon inserts" ON enquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow admin select" ON enquiries FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow admin update" ON enquiries FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow admin delete" ON enquiries FOR DELETE TO authenticated USING (true);
